node-red: remove temporary files from correct directory
* npm.bbclass copies the 'lib' into nonarch_libdir not regular libdir:
  https://git.openembedded.org/openembedded-core/tree/meta/classes-recipe/npm.bbclass?h=scarthgap#n310

* on builds where libdir != nonarch_libdir (e.g. with multilib) this fails, because
  build-tmp-napi-v3 wasn't removed in do_install:

  ERROR: QA Issue: Symlink /usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/node_gyp_bins/python3 in node-red points to TMPDIR [symlink-to-sysroot]
  ERROR: QA Issue: non -staticdev package contains static .a library: node-red path '/usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/Release/nothing.a'
                   non -staticdev package contains static .a library: node-red path '/usr/lib/node_modules/node-red/node_modules/bcrypt/build-tmp-napi-v3/Release/node-addon-api/nothing.a' [staticdev]

* add -v to show in the logs what is being removed

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>