python3-jaraco-functools: remove python3-lang from RDEPENDS
Remove deprecated python3-lang from the RDEPENDS as the
python3-lang package was removed as part of the migration
to the json manifest file. The functionality is now part
of core.

Fix the below yocto compliance issue:
  ERROR: Nothing RPROVIDES 'python3-lang' (but /build/layers/meta-iot-cloud/recipes-devtools/python/python3-jaraco-functools_1.20.bb RDEPENDS on or otherwise requires it)
  NOTE: Runtime target 'python3-lang' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['python3-lang']
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'python3-jaraco-functools', 'python3-lang']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>