rclone/s2n/restic/crc32c: Use SRCREV to replace tag
The tag=v${PV} in SRC_URI doesn't work when add the git sources such as
github.com.awslabs.s2n.git to PREMIRRORS and set BB_NO_NETWORK = "1":

$ bitbake s2n -cfetch

ERROR: s2n-0.10.19-r0 do_fetch: Network access disabled through BB_NO_NETWORK (or set indirectly due to use of BB_FETCH_PREMIRRORONLY) but access requested with command git -c core.fsyncobjectfiles=0 ls-remote git://github.com/awslabs/s2n.git  (for url git://github.com/awslabs/s2n.git)

This is because there is no SRCREV, and bitbake needs check the original url to
get it. And we can't set both tag and SRCREV since bitbake would report that as
conflicts, and compared to SRCREV, tag is not reliable enough since it can be
recreated, so use SRCREV to replace tag.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>